apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argocd
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: operations
        url: https://operations.k8s.local
  template:
    metadata:
      name: '{{cluster}}-argocd'
    spec:
      project: "default"
      sources:
        - repoURL: 'https://github.com/coryleeio/blueprint-fleet-config'
          path: kustomizations/argocd/overlays/{{cluster}}
          targetRevision: HEAD
      destination:
        server: '{{url}}'
        namespace: '{{cluster}}-argocd'
      syncPolicy:
        automated: 
          prune: true
