apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: external-secrets
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: analytics
        url: https://analytics.k8s.local
      - cluster: operations
        url: https://operations.k8s.local
      - cluster: production-eu-west-1
        url: https://production-eu-west-1.k8s.local
      - cluster: production-us-east-1
        url: https://production-us-east-1.k8s.local
  template:
    metadata:
      name: '{{cluster}}-external-secrets'
    spec:
      project: "default"
      sources:
        - repoURL: 'https://charts.external-secrets.io'
          chart: external-secrets
          targetRevision: 0.9.0
          helm:
            releaseName: '{{cluster}}-external-secrets'
            valueFiles:
            - values.yaml
            - $values/helmvalues/external-secrets/values.yaml
            - $values/helmvalues/external-secrets/{{cluster}}.yaml
        - repoURL: 'https://github.com/coryleeio/blueprint-fleet-config'
          targetRevision: HEAD
          ref: values
      destination:
        server: '{{url}}'
        namespace: '{{cluster}}-external-secrets'
      syncPolicy:
        automated: 
          prune: true
          selfHeal: true
