apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: grafana
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: operations
        url: https://operations.k8s.local
  template:
    metadata:
      name: '{{cluster}}-grafana'
    spec:
      project: "default"
      sources:
        - repoURL: 'https://grafana.github.io/helm-charts'
          chart: grafana
          targetRevision: 6.57.4
          helm:
            releaseName: '{{cluster}}-grafana'
            valueFiles:
            - values.yaml
            - values.yaml
            - $values/helmvalues/grafana/values.yaml
            - $values/helmvalues/grafana/{{cluster}}.yaml
        - repoURL: 'https://github.com/coryleeio/blueprint-fleet-config'
          targetRevision: HEAD
          ref: values
      destination:
        server: '{{url}}'
        namespace: '{{cluster}}-grafana'
      syncPolicy:
        automated: 
          prune: true
          selfHeal: true
