apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: operations-argocd

resources: 
  - namespaces.yaml
  - argocd.yaml
  - application-root.yaml
  - cert-manager.yaml
  - prometheus.yaml
  - vault.yaml
  - external-secrets.yaml
  - internal-ingress-nginx.yaml
  - linkerd-crds.yaml
  - linkerd-control-plane.yaml
  - linkerd-viz.yaml
  - grafana.yaml
