apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources: 
  - ../../base
  - ./cert-manager.yaml
  - ./external-secrets.yaml
  - ./prometheus.yaml
  - ./argocd.yaml
  - ./vault.yaml
  - ./internal-ingress-nginx.yaml
  - ./grafana.yaml
  - ./loki.yaml
  - ./promtail.yaml
  - ./tempo.yaml
  - ./kafka.yaml

commonAnnotations:
  linkerd.io/inject: enabled
