adminUser: admin
adminPassword: admin

datasources:
 datasources.yaml:
   apiVersion: 1
   datasources:
    - name: Prometheus
      type: prometheus
      url: http://localdev-prometheus-server.localdev-prometheus.svc.cluster.local:80
      access: proxy
      isDefault: true
    - name: Loki
      type: loki
      url: http://localdev-loki.localdev-loki.svc.cluster.local:3100
      access: proxy
      isDefault: false
    - name: Tempo
      type: tempo
      url: http://localdev-tempo-query-frontend.localdev-tempo.svc.cluster.local:3100
      access: proxy
      isDefault: false
      
dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/default

## Configure grafana dashboard to import
## NOTE: To use dashboards you must also enable/configure dashboardProviders
## ref: https://grafana.com/dashboards
##
## dashboards per provider, use provider name as key.
##
dashboards:
    default:
      node-exporter-full:
        gnetId: 1860
        revision: 31
        datasource: Prometheus
      kube-state-metrics-v2:
        gnetId: 13332
        revision: 12
        datasource: Prometheus
      cadvisor:
        gnetId: 315
        revision: 3
        datasource: Prometheus
      apiserver:
        gnetId: 12006
        revision: 1
        datasource: Prometheus
      core-dns:
        gnetId: 14981
        revision: 2
        datasource: Prometheus
      cert-manager:
        gnetId: 11001
        revision: 1
        datasource: Prometheus
      kafka-topics:
        gnetId: 10122
        revision: 1
        datasource: Prometheus
        
      
  # default:
  #   some-dashboard:
  #     json: |
  #       $RAW_JSON
  #   custom-dashboard:
  #     file: dashboards/custom-dashboard.json
  #   prometheus-stats:
  #     gnetId: 2
  #     revision: 2
  #     datasource: Prometheus
  #   local-dashboard:
  #     url: https://example.com/repository/test.json
  #     token: ''
  #   local-dashboard-base64:
  #     url: https://example.com/repository/test-b64.json
  #     token: ''
  #     b64content: true
  #   local-dashboard-gitlab:
  #     url: https://example.com/repository/test-gitlab.json
  #     gitlabToken: ''
  #   local-dashboard-bitbucket:
  #     url: https://example.com/repository/test-bitbucket.json
  #     bearerToken: ''
  #   local-dashboard-azure:
  #     url: https://example.com/repository/test-azure.json
  #     basic: ''
  #     acceptHeader: '*/*'

