---
{{ readFile "../../environments.yaml" }}

repositories:
- name: linkerd
  url: https://helm.linkerd.io/stable

---
releases:
- name: {{ .Values.name }}
  chart: linkerd/linkerd-crds
  version: {{ .Values.chart_version }}
  installed: {{ .Values.installed }}
  missingFileHandler: Ignore
  namespace: {{ .Values.namespace }}
  forceNamespace: {{ .Values.namespace }}
  values:
  - "values.yaml"
  - "{{ .Environment.Name }}.yaml"
