# this file applies to all environments, only set things here that are expected to be applied uniformly to everything
---
name: vault
namespace: vault
chart_version: 0.24.1
installed: false
ui:
  enabled: true