apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: application-root
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: localdev
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{cluster}}-application-root'
    spec:
      project: "default"
      sources:
        - repoURL: 'https://github.com/coryleeio/blueprint-fleet-config'
          path: 'kustomizations/application-root/overlays/{{cluster}}'
          targetRevision: HEAD
      destination:
        server: '{{url}}'
        namespace: '{{cluster}}-application-root'
      syncPolicy:
        automated: 
          prune: true
