apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: external-secrets
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: localdev
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{cluster}}-external-secrets'
    spec:
      project: "default"
      sources:
        - repoURL: 'https://charts.external-secrets.io'
          chart: external-secrets
          targetRevision: 0.9.0
          helm:
            releaseName: '{{cluster}}-external-secrets'
            valueFiles:
            - values.yaml
            - $values/helmvalues/external-secrets/{{cluster}}.yaml
        - repoURL: 'https://github.com/coryleeio/blueprint-fleet-config'
          targetRevision: HEAD
          ref: values
      destination:
        server: '{{url}}'
        namespace: '{{cluster}}-external-secrets'
