apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kafka
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: localdev
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{cluster}}-kafka'
    spec:
      project: "default"
      sources:
        - repoURL: 'https://charts.bitnami.com/bitnami'
          chart: kafka
          targetRevision: 23.0.2
          helm:
            releaseName: '{{cluster}}-kafka'
            valueFiles:
            - values.yaml
            - values.yaml
            - $values/helmvalues/kafka/values.yaml
            - $values/helmvalues/kafka/{{cluster}}.yaml
        - repoURL: 'https://github.com/coryleeio/blueprint-fleet-config'
          targetRevision: HEAD
          ref: values
      destination:
        server: '{{url}}'
        namespace: '{{cluster}}-kafka'
      syncPolicy:
        automated: 
          prune: true
          selfHeal: true
