apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: linkerd-certificates
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: localdev
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{cluster}}-linkerd-certificates'
    spec:
      project: "default"
      source:
          repoURL: 'https://github.com/coryleeio/blueprint-fleet-config'
          path: 'manifests/{{cluster}}/linkerd-certificates'
          targetRevision: HEAD
      destination:
        server: '{{url}}'
        namespace: 'linkerd'
      syncPolicy:
        automated: 
          prune: true
          selfHeal: true
