apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: linkerd-viz
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: localdev
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{cluster}}-linkerd-viz'
    spec:
      project: "default"
      sources:
        - repoURL: 'https://helm.linkerd.io/stable'
          chart: linkerd-viz
          targetRevision: 30.8.5
          helm:
            releaseName: '{{cluster}}-linkerd-viz'
            valueFiles:
            - values.yaml
            - $values/helmvalues/linkerd-viz/values.yaml
            - $values/helmvalues/linkerd-viz/{{cluster}}.yaml
        - repoURL: 'https://github.com/coryleeio/blueprint-fleet-config'
          targetRevision: HEAD
          ref: values
      destination:
        server: '{{url}}'
        namespace: 'linkerd-viz'
      syncPolicy:
        automated: 
          prune: true
          selfHeal: true
