apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: loki
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: localdev
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{cluster}}-loki'
    spec:
      project: "default"
      sources:
        - repoURL: 'https://grafana.github.io/helm-charts'
          chart: loki
          targetRevision: 5.8.9
          helm:
            releaseName: '{{cluster}}-loki'
            valueFiles:
            - values.yaml
            - values.yaml
            - $values/helmvalues/loki/values.yaml
            - $values/helmvalues/loki/{{cluster}}.yaml
        - repoURL: 'https://github.com/coryleeio/blueprint-fleet-config'
          targetRevision: HEAD
          ref: values
      destination:
        server: '{{url}}'
        namespace: '{{cluster}}-loki'
      syncPolicy:
        automated: 
          prune: true
          selfHeal: true
