apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: promtail
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: localdev
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{cluster}}-promtail'
    spec:
      project: "default"
      sources:
        - repoURL: 'https://grafana.github.io/helm-charts'
          chart: promtail
          targetRevision: 6.11.5
          helm:
            releaseName: '{{cluster}}-promtail'
            valueFiles:
            - values.yaml
            - values.yaml
            - $values/helmvalues/promtail/values.yaml
            - $values/helmvalues/promtail/{{cluster}}.yaml
        - repoURL: 'https://github.com/coryleeio/blueprint-fleet-config'
          targetRevision: HEAD
          ref: values
      destination:
        server: '{{url}}'
        namespace: '{{cluster}}-promtail'
      syncPolicy:
        automated: 
          prune: true
          selfHeal: true
