apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: prometheus
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: localdev
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{cluster}}-prometheus'
    spec:
      project: "default"
      sources:
        - repoURL: 'https://prometheus-community.github.io/helm-charts'
          chart: prometheus
          targetRevision: 22.6.2
          helm:
            releaseName: '{{cluster}}-prometheus'
            valueFiles:
            - values.yaml
            - $values/helmvalues/prometheus/{{cluster}}.yaml
        - repoURL: 'https://github.com/coryleeio/blueprint-fleet-config'
          targetRevision: HEAD
          ref: values
      destination:
        server: '{{url}}'
        namespace: prometheus
