apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources: 
  - ../../base
  - ./cert-manager.yaml
  - ./external-secrets.yaml
  - ./prometheus.yaml
  - ./argocd.yaml
  - ./vault.yaml
  - ./operations.yaml
  - ./kafka.yaml

commonAnnotations:
  linkerd.io/inject: enabled